language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-support
  - extra-android-m2repository

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew

script:
  - "./gradlew assembleRelease"
